export { BackgroundDecor } from './BackgroundDecor/BackgroundDecor'
export { Button } from './Button/Button'
export type { ButtonProps } from './Button/Button'
export { Section } from './Section/Section'
export type { SectionProps } from './Section/Section'
export { SkillIcon } from './SkillIcon/SkillIcon'
export { Tag } from './Tag/Tag'
export type { TagProps } from './Tag/Tag'
